server:
  port: 9000
  servlet:
    context-path: /xigua
spring:
  application:
    name: zuul-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5000/eureka

zuul:
  # 忽略所有微服务名称
  ignored-services: '*'
  # 给访问路径添加统一前缀
  prefix: /atguigu
  routes:
    # 自定义路由规则的名称, 在底层的数据结构中是 Map 的键
    employee:
      # 目标微服务名称, ZuulRoute 类型的一个属性
      service-id: atguigu-feign-consumer
      # 用来代替目标微服务名称的路径
      # /** 表示匹配多层路径, 如果没有加 /**, 则不能匹配后续的多层路径了
      path: /zuul-emp/**
